/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoolingRouteImport } from './routes/pooling'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DemandRouteImport } from './routes/demand'
import { Route as IndexRouteImport } from './routes/index'

const PoolingRoute = PoolingRouteImport.update({
  id: '/pooling',
  path: '/pooling',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandRoute = DemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demand': typeof DemandRoute
  '/driver': typeof DriverRoute
  '/pooling': typeof PoolingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demand': typeof DemandRoute
  '/driver': typeof DriverRoute
  '/pooling': typeof PoolingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demand': typeof DemandRoute
  '/driver': typeof DriverRoute
  '/pooling': typeof PoolingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demand' | '/driver' | '/pooling'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demand' | '/driver' | '/pooling'
  id: '__root__' | '/' | '/demand' | '/driver' | '/pooling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemandRoute: typeof DemandRoute
  DriverRoute: typeof DriverRoute
  PoolingRoute: typeof PoolingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pooling': {
      id: '/pooling'
      path: '/pooling'
      fullPath: '/pooling'
      preLoaderRoute: typeof PoolingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand': {
      id: '/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof DemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemandRoute: DemandRoute,
  DriverRoute: DriverRoute,
  PoolingRoute: PoolingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
